Import('env')


env = env.Clone()
env.Append(
    LIBS=['boost_unit_test_framework'],
    CPPDEFINES=['BOOST_TEST_DYN_LINK'],
)

tests = [
    env.Program('test_interpolate.cpp'),
    env.Program('test_younglaplace.cpp', LIBS=env['LIBS']+['sundials_core', 'sundials_arkode', 'sundials_nvecserial', 'mpi']),
]

Return('tests')
