Import('env')


env = env.Clone(
    tools=['cython'],

    SHLIBPREFIX='',
    SHLIBSUFFIX='$PYTHON_EXT_SUFFIX',
)

env.Append(
    CPPPATH=['$PYTHONINCLUDES'],
    LIBPATH=['$PYTHONLIBPATH'],
    LIBS=['$PYTHONLIB'],
)

env.VariantDir('.checkpoints', '.', duplicate=False)

colorize_c = env.Cython('.checkpoints/colorize.pyx')
colorize = env.SharedLibrary('colorize', colorize_c)

Return('colorize')
