Import('env')


env = env.Clone(
    tools=['cython', 'numpy'],

    SHLIBPREFIX='',
    SHLIBSUFFIX='$PYTHON_EXT_SUFFIX',
)

env.Append(
    CPPPATH=['$PYTHONINCLUDES', '$NUMPYINCLUDES'],
)

env.VariantDir('.checkpoints', '.', duplicate=False)

colorize_c = env.Cython('.checkpoints/colorize.pyx')
colorize = env.SharedLibrary('colorize', colorize_c)

Return('colorize')
