# noinspection PyUnresolvedReferences
from opendrop.app.common.pages import ImageAcquisitionPagePresenter as ConanImageAcquisitionPagePresenter
from .image_processing import ConanImageProcessingPagePresenter
from .results import ConanResultsPagePresenter
